openapi: 3.0.1
info:
  title: Workleap OpenApi MSBuild
  x-cortex-git:
    github:
      alias: gsoft-inc
      repository: gsoft-inc/wl-openapi-msbuild
  x-cortex-tag: service-wl-openapi-msbuild
  x-cortex-type: library
  x-cortex-slack:
    channels:
    - name: internal-dev-platform
      notificationsEnabled: true
  x-cortex-owners:
  - name: team-internal-developer-platform-backend
    type: GROUP
    provider: CORTEX
  x-cortex-link:
  - type: cortex
    url: https://github.com/gsoft-inc/wl-openapi-msbuild/blob/main/.cortex/catalog/service-wl-openapi-msbuild.yaml
    name: Edit current Cortex entity in GitHub

