name: CI

on:
  pull_request:
    branches: ["main", "master"]
    paths-ignore: ["*.md"]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4

      - run: ./Build.ps1
        shell: pwsh

      - run: ./Run-SystemTest.ps1
        shell: pwsh