name: CI

on:
  pull_request:
    branches: ["main", "master"]
    paths-ignore: ["*.md"]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4

      - name: Check if feed is empty
        run: |
          if [ -z "${{  secrets.DO_NOT_EXIST }}" ]; then
            echo "Feed is empty"
          else
            echo "Feed is not empty"
          fi

      - run: ./Build.ps1
        shell: pwsh
        env:
          NUGET_SOURCE: "https://pkgs.dev.azure.com/gsoft/_packaging/gsoftdev/nuget/v3/index.json"
          NUGET_API_KEY: ""

      - run: ./Run-SystemTest.ps1
        shell: pwsh
