name: CI

on:
  pull_request:
    branches: ["main", "master"]
    paths-ignore: ["*.md"]
  
  push:
    branches:
      - "renovate/**"
      - "feature/**"

# Prevent duplicate runs if Renovate falls back to creating a PR
# concurrency:
#   group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
#   cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest


    steps:
      - name: Log GitHub Context Variables
        run: |
          echo "head_ref: ${{ github.head_ref }}"
          echo "ref_name: ${{ github.ref_name }}"
          echo "ref: ${{ github.ref }}"
          echo "sha: ${{ github.sha }}"
          echo "workflow: ${{ github.workflow }}"
          echo "event_name: ${{ github.event_name }}"
          echo "actor: ${{ github.actor }}"
          echo "repository: ${{ github.repository }}"
          echo "repository_owner: ${{ github.repository_owner }}"
          echo "run_id: ${{ github.run_id }}"
          echo "run_number: ${{ github.run_number }}"    

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4
        with:
          source-url: ${{ secrets.NUGET_GSOFTDEV_FEED_URL }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GSOFT_NUGET_API_KEY }}

      - run: ./Build.ps1
        shell: pwsh
        env:
          NUGET_SOURCE: ${{ secrets.NUGET_GSOFTDEV_FEED_URL }}
          NUGET_API_KEY: ${{ secrets.GSOFT_NUGET_API_KEY }}

  linearb:
    needs: [ci]
    uses: gsoft-inc/wl-reusable-workflows/.github/workflows/linearb-deployment.yml@main
    with:
      environment: development
    secrets: inherit
