name: Jira

on:
  pull_request:
    branches: [main]
    paths-ignore: ["*.md"]

jobs:
  call-workflow-jira:
    uses: gsoft-inc/wl-renovate-workflow/.github/workflows/jira-workflow.yml@feature/idp-912_shared_jira_workflow
    with:
      branch_name: $env:GITHUB_HEAD_REF
    secrets: inherit
