name: Semgrep

on:
  pull_request:
    branches: ["main", "master"]
  workflow_dispatch: {}
  schedule:
    - cron: "10 22 * * 6"

jobs:
  call-workflow-semgrep:
    uses: gsoft-inc/wl-reusable-workflows/.github/workflows/reusable-semgrep-workflow.yml@feature/idp-948_shared_semgrep_workflow
    with:
      github_event_name: ${{ github.event_name }}
      github_pr_sha: ${{ github.event.pull_request.base.sha }}
